// Item types
export const ITEM_TYPES = {
  WEAPON: 'weapon',
  ARMOR: 'armor',
  RELIC: 'relic',
};

// Item rarities with their multipliers
export const RARITIES = {
  COMMON: { name: 'Common', multiplier: 1.0, color: 'text-gray-200' },
  UNCOMMON: { name: 'Uncommon', multiplier: 1.2, color: 'text-green-400' },
  RARE: { name: 'Rare', multiplier: 1.5, color: 'text-blue-400' },
  EPIC: { name: 'Epic', multiplier: 1.8, color: 'text-purple-400' },
  LEGENDARY: { name: 'Legendary', multiplier: 2.2, color: 'text-orange-400' },
};

// Stat types
export const STATS = {
  ATTACK: 'attack',
  DEFENSE: 'defense',
  SPEED: 'speed',
  HEALTH: 'health',
  CRITICAL: 'critical', // Critical hit chance
  EVASION: 'evasion', // Chance to evade attacks
};

// Item pool (32 items)
export const ITEM_POOL = [
  // Weapons
  {
    id: 1,
    name: "Whiskerblade",
    description: "A sharp blade forged from the whiskers of ancient cat warriors.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.UNCOMMON,
    stats: { [STATS.ATTACK]: 15, [STATS.SPEED]: 5 },
    icon: "⚔️",
  },
  {
    id: 2,
    name: "Rabbit's Vengeance",
    description: "A ceremonial dagger used by rabbit assassins during the great siege.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.RARE,
    stats: { [STATS.ATTACK]: 18, [STATS.CRITICAL]: 10 },
    icon: "🗡️",
  },
  {
    id: 3,
    name: "Pawmaul",
    description: "Heavy mace that leaves craters shaped like paw prints.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.UNCOMMON,
    stats: { [STATS.ATTACK]: 20, [STATS.SPEED]: -5 },
    icon: "🔨",
  },
  {
    id: 4,
    name: "Feline Fang",
    description: "A curved blade that gleams with ethereal light, taken from fallen royalty.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.EPIC,
    stats: { [STATS.ATTACK]: 25, [STATS.CRITICAL]: 8 },
    icon: "🌙",
  },
  {
    id: 5,
    name: "Carrot Launcher",
    description: "Fires explosive carrots. Limited ammo, unlimited devastation.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.RARE,
    stats: { [STATS.ATTACK]: 22, [STATS.SPEED]: 3 },
    icon: "🥕",
  },
  {
    id: 6,
    name: "Whisper of Ashes",
    description: "A bow made from the charred remains of the first kingdom to fall.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.EPIC,
    stats: { [STATS.ATTACK]: 22, [STATS.SPEED]: 8 },
    icon: "🏹",
  },
  {
    id: 7,
    name: "Royal Scepter",
    description: "Once wielded by the Cat King, now just a reminder of fallen glory.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.LEGENDARY,
    stats: { [STATS.ATTACK]: 30, [STATS.HEALTH]: 10 },
    icon: "👑",
  },
  {
    id: 8,
    name: "Burrow Drill",
    description: "The rabbits' siege weapon that broke through the final walls.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.EPIC,
    stats: { [STATS.ATTACK]: 28, [STATS.DEFENSE]: -5 },
    icon: "⚙️",
  },
  {
    id: 9,
    name: "Clawed Gauntlet",
    description: "Metal claws that mimic the strength of the ancient cat warriors.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.UNCOMMON,
    stats: { [STATS.ATTACK]: 16, [STATS.SPEED]: 6 },
    icon: "👊",
  },
  {
    id: 10,
    name: "Wasteland Scythe",
    description: "A farming tool repurposed for war, stained with the blood of both sides.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.RARE,
    stats: { [STATS.ATTACK]: 21, [STATS.CRITICAL]: 7 },
    icon: "🪓",
  },
  {
    id: 11,
    name: "Broken Promise",
    description: "A shattered sword representing the peace treaties that never lasted.",
    type: ITEM_TYPES.WEAPON,
    rarity: RARITIES.LEGENDARY,
    stats: { [STATS.ATTACK]: 32, [STATS.DEFENSE]: -8 },
    icon: "💔",
  },
  
  // Armors
  {
    id: 12,
    name: "Fur-lined Breastplate",
    description: "Standard issue armor for cat infantry, offering decent protection.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.COMMON,
    stats: { [STATS.DEFENSE]: 18, [STATS.SPEED]: -2 },
    icon: "🛡️",
  },
  {
    id: 13,
    name: "Warren Guardian",
    description: "Light armor favored by rabbit scouts for its mobility.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.UNCOMMON,
    stats: { [STATS.DEFENSE]: 14, [STATS.SPEED]: 7 },
    icon: "🦺",
  },
  {
    id: 14,
    name: "Siege Captain's Plate",
    description: "Heavy armor worn by the commanders who led the final charge.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.RARE,
    stats: { [STATS.DEFENSE]: 25, [STATS.HEALTH]: 15, [STATS.SPEED]: -7 },
    icon: "⛓️",
  },
  {
    id: 15,
    name: "Whisker Woven Mail",
    description: "Lightweight armor that deflects blows with surprising strength.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.EPIC,
    stats: { [STATS.DEFENSE]: 22, [STATS.EVASION]: 8 },
    icon: "🧵",
  },
  {
    id: 16,
    name: "Burrow Digger's Attire",
    description: "Reinforced gauntlets and kneepads made for siege tunnelling.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.UNCOMMON,
    stats: { [STATS.DEFENSE]: 16, [STATS.HEALTH]: 10 },
    icon: "🧤",
  },
  {
    id: 17,
    name: "Royal Guard Regalia",
    description: "Ornate yet functional armor worn by the personal guards of the Cat King.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.LEGENDARY,
    stats: { [STATS.DEFENSE]: 30, [STATS.HEALTH]: 20, [STATS.SPEED]: -5 },
    icon: "🏆",
  },
  {
    id: 18,
    name: "Shadow Weave",
    description: "Dark cloth armor that makes the wearer nearly invisible in shadows.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.RARE,
    stats: { [STATS.DEFENSE]: 15, [STATS.EVASION]: 15, [STATS.SPEED]: 5 },
    icon: "🕸️",
  },
  {
    id: 19,
    name: "Ironpelt Harness",
    description: "Sturdy but heavy armor made from scavenged battlefield metal.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.COMMON,
    stats: { [STATS.DEFENSE]: 20, [STATS.SPEED]: -4 },
    icon: "🔗",
  },
  {
    id: 20,
    name: "Wasteland Scavenger's Coat",
    description: "Patchwork armor offering moderate protection against both weather and weapons.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.COMMON,
    stats: { [STATS.DEFENSE]: 15, [STATS.HEALTH]: 8 },
    icon: "🧥",
  },
  {
    id: 21,
    name: "Last Stand Plate",
    description: "Armor that grows stronger as the wearer's health diminishes.",
    type: ITEM_TYPES.ARMOR,
    rarity: RARITIES.EPIC,
    stats: { [STATS.DEFENSE]: 24, [STATS.HEALTH]: -5, [STATS.ATTACK]: 5 },
    icon: "☠️",
  },
  
  // Relics
  {
    id: 22,
    name: "Pawprint Amulet",
    description: "A charm bearing the mark of the ancient cat dynasty.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.UNCOMMON,
    stats: { [STATS.HEALTH]: 15, [STATS.EVASION]: 5 },
    icon: "🐾",
  },
  {
    id: 23,
    name: "Burrow Heart Stone",
    description: "A glowing gem from deep underground, strengthening the bearer's resolve.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.RARE,
    stats: { [STATS.HEALTH]: 20, [STATS.DEFENSE]: 8 },
    icon: "💎",
  },
  {
    id: 24,
    name: "Shattered Crown",
    description: "Remnant of a ruler who lost everything to hubris.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.EPIC,
    stats: { [STATS.ATTACK]: 10, [STATS.CRITICAL]: 15 },
    icon: "👑",
  },
  {
    id: 25,
    name: "Emblem of Broken Truce",
    description: "Symbol of betrayal that now grants power to its wielder.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.RARE,
    stats: { [STATS.ATTACK]: 12, [STATS.SPEED]: 10 },
    icon: "⚜️",
  },
  {
    id: 26,
    name: "Remembrance Locket",
    description: "Contains images of loved ones lost in the endless war.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.COMMON,
    stats: { [STATS.HEALTH]: 12, [STATS.DEFENSE]: 5 },
    icon: "🔖",
  },
  {
    id: 27,
    name: "Echo of the Fallen",
    description: "Whispers strategies of the dead when danger is near.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.EPIC,
    stats: { [STATS.EVASION]: 18, [STATS.SPEED]: 12 },
    icon: "👂",
  },
  {
    id: 28,
    name: "Desolation Timepiece",
    description: "A watch that stopped the moment the world was forever changed.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.LEGENDARY,
    stats: { [STATS.SPEED]: 20, [STATS.CRITICAL]: 10, [STATS.EVASION]: 10 },
    icon: "⏱️",
  },
  {
    id: 29,
    name: "Siege Horn",
    description: "The sound that announced the final battle, now a relic of power.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.RARE,
    stats: { [STATS.ATTACK]: 8, [STATS.SPEED]: 8, [STATS.DEFENSE]: 8 },
    icon: "📯",
  },
  {
    id: 30,
    name: "Ashen Treaty",
    description: "The burned remains of an agreement that might have saved both sides.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.UNCOMMON,
    stats: { [STATS.HEALTH]: 10, [STATS.DEFENSE]: 10 },
    icon: "📜",
  },
  {
    id: 31,
    name: "Wasteland Compass",
    description: "Always points to safety, if such a thing still exists.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.COMMON,
    stats: { [STATS.EVASION]: 12, [STATS.SPEED]: 5 },
    icon: "🧭",
  },
  {
    id: 32,
    name: "Heart of the Kingdom",
    description: "The last remnant of a once-great civilization, pulsing with ancient magic.",
    type: ITEM_TYPES.RELIC,
    rarity: RARITIES.LEGENDARY,
    stats: { [STATS.HEALTH]: 25, [STATS.ATTACK]: 12, [STATS.DEFENSE]: 12 },
    icon: "❤️",
  },
];

// Game constants
export const ITEMS_PER_POOL = 6;
export const ITEMS_TO_SELECT = 3;
export const BASE_STATS = {
  [STATS.HEALTH]: 100,
  [STATS.ATTACK]: 20,
  [STATS.DEFENSE]: 10,
  [STATS.SPEED]: 10,
  [STATS.CRITICAL]: 5, // 5% base critical chance
  [STATS.EVASION]: 5, // 5% base evasion chance
}; 